---
- name: Install Kubernetes-Components
  hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install kubelet, kubeadm, kubectl, containerd
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - containerd
        state: present

    - name: Hold Kubernetes-Packages
      ansible.builtin.command: apt-mark hold {{ item }}
      loop:
        - kubelet
        - kubeadm
        - kubectl
