# /etc/netplan
# 99-ccnet.yaml

network:
    ethernets:
        enp0s9:
            dhcp4: false
            addresses: [192.168.0.101/24] # for each VM!
            routes:
              - to: 0.0.0.0/0
                via: 192.168.0.1
            nameservers:
              addresses: [192.168.0.1]
    version: 2
