---
- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  become: true
  vars:
    pod_network_cidr: "10.244.0.0/16"
  tasks:
    - name: Check, if kubadm init ran
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_init_done

    - name: Run kubeadm init
      ansible.builtin.command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_host }}
        --pod-network-cidr={{ pod_network_cidr }}
      when: not kubeadm_init_done.stat.exists
