---
- name: Configure sysctl
  hosts: all
  become: true
  tasks:
    - name: Deploy sysctl config from template
      ansible.builtin.template:
        src: k8s.conf.j2
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
      notify: Apply sysctl settings

    - name: Autoboot modules br_netfilter, overlay
      ansible.builtin.template:
        src: containerd.conf.j2
        dest: /etc/modules-load.d/containerd.conf
        owner: root
        group: root
        mode: '0644'
      notify: Apply sysctl settings

  handlers:
    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system
